server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://1.15.88.192:3306/zudi?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql=true:
    redis:
      host: 1.15.88.192
      port: 6379

#开启knife4j增强
knife4j:
  enable: true
